.\" $Id: sctd.1 18 2017-05-12 21:02:19Z umaxx $
.\" Copyright (c) 2017 Joerg Jung <mail@umaxx.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd May 12, 2017
.Dt SCTD 1
.Os
.Sh NAME
.Nm sctd
.Nd daemon to shift color temperature of the screen
.Sh SYNOPSIS
.Nm sctd
.Nm sctd
.Cm version
.Sh DESCRIPTION
.Nm
is a lightweight daemon wrapper script around
.Xr sct 1 .
The color temperature of the screen is increased or decreased dynamically
depending on the current time of the day.
.Pp
The arguments are as follows:
.Bl -tag -width "version"
.It Cm version
Print the
.Cm version
and copyright information of
.Nm
to the standard output, then exit.
.El
.Pp
.Nm
does not expect any arguments.
The default temperature value is 4500 and incremented or decremented in steps
of two every minute.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Run
.Nm
to shift the screen temperature dynamically:
.Bd -literal -offset indent
$ sctd
.Ed
.Pp
Print
.Cm version
and copyright information of
.Nm
to the standard output stream and exit successfully:
.Bd -literal -offset indent
$ sctd version
.Ed
.Sh SEE ALSO
.Xr sct 1
.Sh STANDARDS
The
.Nm
utility is not compliant with any specification.
.Pp
Where portability is paramount, do not use it.
.Sh HISTORY
The first version of the
.Nm
utility appeared back in May 2017 in the following Lobsters article:
.Lk https://lobste.rs/s/stlowv/sctd_minimal_daemon_for_sct .
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Aaron Bieber Aq Mt abieber@openbsd.org
and further improved by
.An Joerg Jung Aq Mt jung@openbsd.org .
.Sh CAVEATS
Since
.Xr sct 1
rounds the given values in steps of 500, the sctd adjusts the screen
temperature only about every 4 hours.
.Sh HOMEPAGE
.Lk https://www.umaxx.net/
